/**
 * Append-only writeback for `VERIFICATION.md` in the project's working
 * directory. Triggered by the daemon after a task transitions to
 * `completed` or `failed`, so `verifyCommand` results become a searchable,
 * grep-able record outside the `~/.axi-todo/tasks.json` JSON store.
 *
 * The contract:
 *   - Path: `<task.cwd>/VERIFICATION.md` (root, not `docs/VERIFICATION.md`,
 *     to match the existing `documents.verification = "VERIFICATION.md"`
 *     contract added on 2026-06-11).
 *   - By default, writeback only appends to an existing `VERIFICATION.md`.
 *     Set `AXI_TODO_VERIFY_LOG_CREATE=1` to allow first-write creation.
 *   - Paths under `references/` or archive folders are skipped to avoid
 *     mutating third-party/reference checkouts.
 *   - Each entry is a single bullet line, idempotent on `<taskId> +
 *     <checkedAt>` (re-running the same task does not duplicate).
 *   - All writes are wrapped in try/catch: failure to write back NEVER
 *     propagates up to the daemon, because the JSON store already
 *     captured the result.
 */
import fs from "node:fs/promises";
import path from "node:path";

const VERIFICATION_FILENAME = "VERIFICATION.md";
const SECTION_HEADING = "## Axi Todo Verify Activity";
const FRONTMATTER = [
  "<!-- Layer: 3 | Verification | Module: project-axi-todo-writeback -->",
  "<!-- Auto-generated by axi-todo daemon. Safe to edit comments; do not delete the section heading. -->",
  "",
  "# Verification",
  "",
].join("\n");

/**
 * Append one verification entry to `<cwd>/VERIFICATION.md`. Resolves with
 * `true` when the file was written, `false` when nothing was written
 * (e.g. task has no verifyCommand, file is unreachable, or entry is a
 * duplicate). Never throws.
 *
 * @param {object} args
 * @param {object} args.task    - axi-todo task snapshot (need id, title, cwd, verifyCommand, status)
 * @param {object} args.result  - executor result (need verification {status, exitCode, checkedAt, output})
 * @param {string} [args.now]   - ISO timestamp; defaults to task.verification.checkedAt
 */
export async function appendVerificationLogEntry({ task, result, now, env = process.env } = {}) {
  if (!task || typeof task !== "object") return false;
  if (!task.cwd || !task.verifyCommand) return false;
  const verification = result?.verification;
  if (!verification) return false;

  const cwd = String(task.cwd);
  if (!isWritebackPathAllowed(cwd)) return false;
  let target;
  try {
    target = path.resolve(cwd, VERIFICATION_FILENAME);
    await fs.access(path.dirname(target));
  } catch {
    // cwd does not exist (e.g. ephemeral task); silently skip
    return false;
  }

  const checkedAt = verification.checkedAt || now || new Date().toISOString();
  // Dedupe signature: the rendered entry line always contains the literal
  // `` `<taskId>` `` token followed by the status and checkedAt. Using the
  // full line (taskId + checkedAt) is robust against re-ordering and
  // re-renders of the same task run.
  const dedupeSignature = `${checkedAt} | \`${task.id}\` | ${verification.status || (result?.success ? "passed" : "failed")} | exit=${verification.exitCode ?? "?"}`;

  let existing = "";
  try {
    existing = await fs.readFile(target, "utf8");
  } catch (error) {
    if (error.code !== "ENOENT") {
      // Read failed for non-missing reasons; bail without propagating
      return false;
    }
    if (!allowsCreate(env)) return false;
  }

  if (existing.includes(dedupeSignature)) {
    return false;
  }

  const entry = formatEntryLine({ task, result, verification, checkedAt });
  let next;
  if (!existing) {
    next = `${FRONTMATTER}${SECTION_HEADING}\n\n${entry}\n`;
  } else if (existing.includes(SECTION_HEADING)) {
    next = appendUnderHeading(existing, entry);
  } else {
    // File exists but lacks our section. Append the heading + entry, keeping
    // any pre-existing content (often `Last Verified:` frontmatter).
    next = `${existing.replace(/\s*$/, "")}\n\n${SECTION_HEADING}\n\n${entry}\n`;
  }

  try {
    await fs.writeFile(target, next, "utf8");
  } catch {
    // Filesystem refused (read-only, etc.). The JSON store has the truth.
    return false;
  }
  return true;
}

function allowsCreate(env) {
  return /^(1|true|yes)$/i.test(String(env?.AXI_TODO_VERIFY_LOG_CREATE || ""));
}

function isWritebackPathAllowed(cwd) {
  const normalized = path.resolve(String(cwd));
  const parts = normalized.split(path.sep).filter(Boolean);
  if (parts.includes("references")) return false;
  return !parts.some((part) => part.startsWith("_cleanup-archive"));
}

function formatEntryLine({ task, result, verification, checkedAt }) {
  const status = verification.status || (result?.success ? "passed" : "failed");
  const exit = verification.exitCode ?? "?";
  const command = String(task.verifyCommand).replace(/`/g, "\\`");
  const title = String(task.title || task.id).replace(/\|/g, "\\|").slice(0, 80);
  // Surface runner warnings (e.g. `codex-stdout-truncated-dropped-12kb`) as a
  // tail annotation on the entry. We only render when the warnings are
  // non-empty so the line shape is identical to before for healthy runs.
  const warningList = Array.isArray(verification.warnings) ? verification.warnings : [];
  const warningTail = warningList.length > 0
    ? ` | ⚠ ${warningList.length} warning${warningList.length === 1 ? "" : "s"}: ${warningList.join("; ")}`
    : "";
  return `- ${checkedAt} | \`${task.id}\` | ${status} | exit=${exit} | ${title} | \`${command}\`${warningTail}`;
}

function appendUnderHeading(text, entry) {
  // Find the section heading line and insert the new entry as the FIRST
  // bullet after the heading. This keeps the reverse-chronological order
  // stable (newest first) regardless of whitespace.
  const lines = text.split(/\r?\n/);
  const headingIndex = lines.findIndex((line) => line.trim() === SECTION_HEADING);
  if (headingIndex === -1) {
    return `${text.replace(/\s*$/, "")}\n\n${SECTION_HEADING}\n\n${entry}\n`;
  }
  // Walk forward: skip blank lines; stop before the first non-blank line
  // OR the next sibling heading. Insert immediately before that line.
  let insertAt = lines.length;
  for (let i = headingIndex + 1; i < lines.length; i += 1) {
    const line = lines[i];
    if (/^#{1,6}\s+/.test(line)) {
      insertAt = i;
      break;
    }
    if (line.trim() !== "") {
      insertAt = i;
      break;
    }
  }
  lines.splice(insertAt, 0, entry);
  return `${lines.join("\n").replace(/\s*$/, "")}\n`;
}

/**
 * Parse the `## Axi Todo Verify Activity` section of `<cwd>/VERIFICATION.md`
 * and return entries as structured rows. Newest first; capped by `limit`.
 * Always resolves; returns [] when the file or section is missing.
 *
 * @param {object} args
 * @param {string} args.cwd   - project working directory
 * @param {number} [args.limit=32]
 * @returns {Promise<Array<{checkedAt, taskId, status, exitCode, title, command}>>}
 */
export async function readVerificationLogEntries({ cwd, limit = 32 } = {}) {
  if (!cwd) return [];
  const target = path.resolve(String(cwd), VERIFICATION_FILENAME);
  let text = "";
  try {
    text = await fs.readFile(target, "utf8");
  } catch {
    return [];
  }
  const lines = text.split(/\r?\n/);
  const headingIndex = lines.findIndex((line) => line.trim() === SECTION_HEADING);
  if (headingIndex === -1) return [];

  // New entries may carry a trailing `| ⚠ N warning(s): <text>` segment;
  // older entries do not. We make the tail optional so legacy lines still
  // parse cleanly.
  const entryPattern = /^-\s+(\S+)\s+\|\s+`([^`]+)`\s+\|\s+(\S+)\s+\|\s+exit=([^\s|]+)\s+\|\s+([^|]+?)\s+\|\s+`([^`]+)`(?:\s+\|\s+⚠\s+(\d+)\s+warning(?:s)?:\s+(.+))?\s*$/;
  const entries = [];
  for (let i = headingIndex + 1; i < lines.length; i += 1) {
    const line = lines[i];
    if (/^#{1,6}\s+/.test(line)) break;
    const match = line.match(entryPattern);
    if (!match) continue;
    const warnings = match[7]
      ? match[8].split(";").map((entry) => entry.trim()).filter(Boolean)
      : [];
    entries.push({
      checkedAt: match[1],
      taskId: match[2],
      status: match[3],
      exitCode: match[4] === "?" ? null : Number.parseInt(match[4], 10),
      title: match[5].trim(),
      command: match[6],
      warnings,
    });
  }
  entries.sort((left, right) => right.checkedAt.localeCompare(left.checkedAt));
  return entries.slice(0, limit);
}
